### ISSUE TITLE
Two errors: workflow.ts and edge.ts

### ISSUE THREAD

**Issue by esanzgar** [rabix/cwl-svg#26]
Steps:
1. Clone project 
2. `npm install`
3. `npm run webpack:watch`

Get:
ERROR in ./src/graph/workflow.ts
(1368,25): error TS2365: Operator '===' cannot be applied to types 'void' and 'boolean'.

ERROR in ./src/graph/edge.ts
(43,32): error TS2339: Property 'isValid' does not exist on type 'Edge'.

**Comment by ivanbatic** [comment]
This should be fixed with https://github.com/rabix/cwl-svg/commit/d440bf0522ecc24e137828035c2d443be847364d
