### ISSUE TITLE
Is is possible to make the the svg not interactive?

### ISSUE THREAD

**Issue by esanzgar** [rabix/cwl-svg#27]
I just want to display a workflow without giving the users the option of any interactive functionality.

Is that possible?

Thanks

**Comment by ivanbatic** [comment]
At the moment no, sorry.
This is something that we are working on (as a part of plugin-based architecture) at the moment and expect it to land on master in the following weeks.

**Comment by ivanbatic** [comment]
@esanzgar Hey, there's an update.
Since version 2.0.0, all interactions are made as plugins, so you can now have a non-interactive display. There's a new example in README, and a comment in https://github.com/rabix/cwl-svg/issues/32
