### ISSUE TITLE
Visualise cwl from the cwl-samples folder 

### ISSUE THREAD

**Issue by esanzgar** [rabix/cwl-svg#28]
Using the demo, how can I visualise workflow examples from the cwl-samples directory?

**Comment by ivanbatic** [comment]
You can locally edit the demo file https://github.com/rabix/cwl-svg/blob/master/src/demo.ts#L10
and change
```typescript
const wf = WorkflowFactory.from(samples.bcBio);
```
to
```typescript
const wf = WorkflowFactory.from(samples.fastQC);
```
