### ISSUE TITLE
conversion from yml to json

### ISSUE THREAD

**Issue by m-gall** [rabix/cwl-svg#33]
Hi rabix,
I am trying to implement the svg library as part of a website. It seems the library expects the CWL to be formatted in the sbg json format, rather than accepting as the yaml format. Is there any way of automating this process (other than uploading to Sevenbridges platform - which is manual and slow). Perhaps this can be performed as part of bunny?
I think the tools are great. Thanks.

**Comment by ivanbatic** [comment]
Hi,

Workflow constructor for this library requires a CWL-TS model.
If you have a JSON object, you can create that model like the demo does.
```
const model = WorkflowFactory.from({
   class: "Workflow",
    ...
});
```

If you have Yaml strings, you can convert them to javascript objects by using a library like [js-yaml](https://github.com/nodeca/js-yaml)

And then load it with 
```
const yamlContent = `
id: hello
class: Workflow
...
`
const jsonObject = yaml.safeLoad(yamlContent, {json: true})
const model = WorkflowFactory.from(jsonObject)
```
