### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by azzaea** [rabix/cwl-svg#38]
Hello,

Thank you for your work on this library- it is really neat! I'm writing a comparative paper on workflow engines, and thought to cite your work. Would you advise on how to do so?

Thanks,
Azza

**Comment by azzaea** [comment]
Hello again,
Any update on this?

**Comment by ghost** [comment]
Hello! 

Sorry, for the late response. 

`cwl-svg` is not a workflow engine, but rather a visualizer for workflows expressed in Common Workflow Language.

That said, if you wish to cite `cwl-svg` you can use the following information

```
CWL-SVG: an open-source workflow visualization library for the 
Common Workflow Language., Seven Bridges/Rabix (2017)  
Available from https://github.com/rabix/cwl-svg
```

Thank you!

**Comment by azzaea** [comment]
Nice- thank you! Yes, I referred to helper tools, and this was too cool to miss.
